[build]
  publish = "public/"
  command = "npm run build"
[build.processing]
    skip_processing = false
[build.processing.html]
    minify = true
    pretty_urls = true
[[redirects]]
    from = "https://patrickw.netlify.app"
    to = "https://pad.wtf"
    status = 301
    force = true
